import type { QuizQuestion } from './types';

export const questions: QuizQuestion[] = [
  {
    id: 'basic-cluster-meaning',
    type: 'multiple-choice',
    section: '쿠버네티스 기본 구조',
    prompt: '쿠버네티스에서 클러스터(Cluster)를 가장 정확히 설명한 것은?',
    options: [
      '하나의 컨테이너 이미지를 저장하는 레지스트리',
      '여러 노드로 구성된 쿠버네티스의 운영 단위',
      '외부 도메인을 Service로 연결하는 HTTP 규칙',
      'Pod 내부에서 실행되는 단일 프로세스',
    ],
    correctAnswer: '여러 노드로 구성된 쿠버네티스의 운영 단위',
    explanation: '문서에서는 클러스터를 쿠버네티스의 전체 구성 단위이자 여러 노드들의 집합으로 설명한다.',
  },
  {
    id: 'basic-control-plane-role',
    type: 'multiple-choice',
    section: '쿠버네티스 기본 구조',
    prompt: 'Control Plane이 담당하는 역할은 무엇인가?',
    options: [
      '실제 애플리케이션 컨테이너만 실행한다.',
      '클러스터 상태 관리, 스케줄링, API 서버 운영을 담당한다.',
      '외부 로드 밸런서의 IP만 관리한다.',
      '컨테이너 이미지를 빌드한다.',
    ],
    correctAnswer: '클러스터 상태 관리, 스케줄링, API 서버 운영을 담당한다.',
    explanation: 'Control Plane은 클러스터 제어를 담당하며 운영 환경에서는 고가용성 구성이 중요하다.',
  },
  {
    id: 'basic-pod-smallest-unit',
    type: 'true-false',
    section: '쿠버네티스 기본 구조',
    prompt: 'Pod는 쿠버네티스의 가장 작은 배포 단위이며 하나 이상의 컨테이너를 포함할 수 있다.',
    correctAnswer: true,
    explanation: '문서에서는 Pod를 가장 작은 배포 단위이자 컨테이너 바구니로 설명한다.',
  },
  {
    id: 'basic-worker-workload',
    type: 'fill-blank',
    section: '쿠버네티스 기본 구조',
    prompt: '실제 애플리케이션 컨테이너가 배포되어 workload를 실행하는 노드는 ____ Node이다.',
    correctAnswer: ['Worker', 'Worker Node', '워커', '워커 노드'],
    explanation: 'Worker Node는 실제 애플리케이션의 workload를 실행하는 노드다.',
  },
  {
    id: 'deployment-role',
    type: 'multiple-choice',
    section: 'Deployment',
    prompt: 'Deployment의 주된 역할로 맞는 것은?',
    options: [
      '파드의 원하는 상태를 정의하고 복제 수와 배포를 관리한다.',
      '브라우저의 HTTPS 인증서를 발급한다.',
      '클러스터 외부 DNS만 갱신한다.',
      'Pod IP를 고정된 물리 IP로 바꾼다.',
    ],
    correctAnswer: '파드의 원하는 상태를 정의하고 복제 수와 배포를 관리한다.',
    explanation: 'Deployment는 ReplicaSet을 생성해 Pod를 일정 개수로 유지하고 롤링 업데이트와 롤백을 관리한다.',
  },
  {
    id: 'deployment-replicaset',
    type: 'true-false',
    section: 'Deployment',
    prompt: 'Deployment는 내부적으로 ReplicaSet을 만들어 Pod를 일정 개수로 유지한다.',
    correctAnswer: true,
    explanation: '문서의 핵심 3요소 설명에서 Deployment가 내부적으로 ReplicaSet을 만든다고 정리되어 있다.',
  },
  {
    id: 'traffic-flow-order',
    type: 'ordering',
    section: '트래픽 흐름',
    prompt: '외부 요청이 애플리케이션 컨테이너까지 도달하는 흐름을 순서대로 배열하세요.',
    items: ['Pod', 'Ingress', 'Service'],
    correctAnswer: ['Ingress', 'Service', 'Pod'],
    explanation: '문서의 트래픽 흐름은 External Request, Ingress, Service, Pod 순서다.',
  },
  {
    id: 'docker-build-command',
    type: 'fill-blank',
    section: '배포 흐름',
    prompt: '현재 디렉터리의 Dockerfile로 `my-app:latest` 이미지를 빌드하는 명령어는?',
    correctAnswer: ['docker build -t my-app:latest .'],
    explanation: '문서의 Dockerfile 단계 예시는 `docker build -t my-app:latest .`이다.',
  },
  {
    id: 'registry-reason',
    type: 'short-answer',
    section: '배포 흐름',
    prompt: '빌드한 이미지를 Registry에 업로드해야 하는 이유를 짧게 쓰세요.',
    correctAnswer: [
      '쿠버네티스 클러스터에서 이미지를 사용할 수 있게 하기 위해',
      '클러스터에서 이미지를 사용할 수 있게 하기 위해',
      '클러스터가 이미지를 가져올 수 있게 하기 위해',
    ],
    explanation: 'Deployment가 참조하는 이미지는 클러스터가 접근 가능한 Registry에 있어야 한다.',
  },
  {
    id: 'deployment-apply',
    type: 'fill-blank',
    section: '배포 흐름',
    prompt: '`deployment.yaml`을 클러스터에 적용하는 명령어는?',
    correctAnswer: ['kubectl apply -f deployment.yaml'],
    explanation: '문서에서는 `kubectl apply -f deployment.yaml`로 Deployment 설정을 적용한다고 설명한다.',
  },
  {
    id: 'service-purpose',
    type: 'multiple-choice',
    section: 'Service',
    prompt: 'Service가 필요한 주된 이유는 무엇인가?',
    options: [
      'Pod IP가 변해도 고정된 접근 지점과 로드밸런싱을 제공하기 위해',
      'Dockerfile을 자동으로 생성하기 위해',
      'Control Plane을 워커 노드로 바꾸기 위해',
      'Kibana 대시보드를 생성하기 위해',
    ],
    correctAnswer: 'Pod IP가 변해도 고정된 접근 지점과 로드밸런싱을 제공하기 위해',
    explanation: 'Service는 동적으로 변하는 Pod 집합 앞에 고정 IP/DNS와 로드밸런싱을 제공한다.',
  },
  {
    id: 'service-default-type',
    type: 'multiple-choice',
    section: 'Service',
    prompt: 'Service의 기본 타입이며 클러스터 내부에서만 접근 가능한 것은?',
    options: ['NodePort', 'ClusterIP', 'LoadBalancer', 'Gateway'],
    correctAnswer: 'ClusterIP',
    explanation: 'ClusterIP는 클러스터 내부망에서만 접근 가능한 Service의 기본 타입이다.',
  },
  {
    id: 'service-nodeport-access',
    type: 'true-false',
    section: 'Service',
    prompt: 'NodePort는 각 노드의 특정 포트를 통해 서비스를 외부에 노출할 수 있다.',
    correctAnswer: true,
    explanation: '문서에서는 NodePort가 `http://<Node IP>:<NodePort>` 방식의 외부 접근을 제공한다고 설명한다.',
  },
  {
    id: 'service-loadbalancer-cloud',
    type: 'multiple-choice',
    section: 'Service',
    prompt: 'LoadBalancer 타입에 대한 설명으로 맞는 것은?',
    options: [
      '클라우드 제공자의 외부 로드 밸런서를 프로비저닝해 서비스와 연결한다.',
      '클러스터 내부에서만 접근 가능한 가상 IP를 만든다.',
      'Pod의 컨테이너 로그를 출력한다.',
      'Nginx location 블록에만 설정을 추가한다.',
    ],
    correctAnswer: '클라우드 제공자의 외부 로드 밸런서를 프로비저닝해 서비스와 연결한다.',
    explanation: 'LoadBalancer는 AWS, GCP, Azure 같은 클라우드 환경에서 외부 로드 밸런서를 연결하는 타입이다.',
  },
  {
    id: 'service-coredns',
    type: 'fill-blank',
    section: 'Service',
    prompt: '쿠버네티스 내부에서 Service 이름을 IP 정보로 해석해 주는 내장 DNS는 ____이다.',
    correctAnswer: ['CoreDNS', 'core dns'],
    explanation: '문서에서는 CoreDNS가 Service 이름을 파드 IP 목록으로 자동 변환해 준다고 설명한다.',
  },
  {
    id: 'service-endpoint',
    type: 'short-answer',
    section: 'Service',
    prompt: 'Endpoint가 무엇인지 한 문장으로 설명하세요.',
    correctAnswer: [
      '서비스가 실제 연결할 파드들의 IP와 포트 정보 목록',
      'Service가 실제 연결할 Pod의 IP와 포트 정보 목록',
      '실제 연결할 파드 IP와 포트 목록',
    ],
    explanation: 'Endpoint는 Service의 논리적 이름 뒤에 있는 실제 대상 Pod IP와 포트 목록이다.',
  },
  {
    id: 'service-command-match',
    type: 'matching',
    section: 'kubectl 명령어',
    prompt: 'Service 관련 명령어와 용도를 연결하세요.',
    pairs: [
      { left: 'kubectl get svc', right: 'Service 목록 조회' },
      { left: 'kubectl describe svc <service-name>', right: 'Service 상세 정보 조회' },
      { left: 'kubectl port-forward svc/<service-name> <local-port>:<service-port>', right: '로컬 포트 포워딩' },
    ],
    correctAnswer: {
      'kubectl get svc': 'Service 목록 조회',
      'kubectl describe svc <service-name>': 'Service 상세 정보 조회',
      'kubectl port-forward svc/<service-name> <local-port>:<service-port>': '로컬 포트 포워딩',
    },
    explanation: '문서의 Service 명령어 표는 목록 조회, 상세 조회, 로컬 포트 포워딩을 구분한다.',
  },
  {
    id: 'ingress-purpose',
    type: 'multiple-choice',
    section: 'Ingress',
    prompt: 'Ingress를 도입하는 핵심 이유는?',
    options: [
      '도메인 기반 라우팅, SSL 종단점 처리, 경로 분기를 위해',
      'Pod 내부 컨테이너 개수를 고정하기 위해',
      'Docker 이미지를 직접 빌드하기 위해',
      'Request와 Limit을 자동으로 계산하기 위해',
    ],
    correctAnswer: '도메인 기반 라우팅, SSL 종단점 처리, 경로 분기를 위해',
    explanation: '문서에서는 외부 노출 요구사항 때문에 Ingress가 도메인 라우팅, SSL, Path 분기를 담당한다고 설명한다.',
  },
  {
    id: 'ingress-controller-rule',
    type: 'true-false',
    section: 'Ingress',
    prompt: 'Ingress는 규칙이고, Ingress Controller가 이 규칙을 실제로 실행한다.',
    correctAnswer: true,
    explanation: 'Ingress 자체는 설정이며 Nginx 같은 Ingress Controller가 실제 라우팅 엔진 역할을 한다.',
  },
  {
    id: 'ingress-observability-order',
    type: 'ordering',
    section: 'Ingress',
    prompt: 'Ingress 로그 수집 파이프라인을 순서대로 배열하세요.',
    items: ['Kibana', 'FluentD', 'Nginx Ingress', 'ElasticSearch'],
    correctAnswer: ['Nginx Ingress', 'FluentD', 'ElasticSearch', 'Kibana'],
    explanation: '문서의 관측성 파이프라인은 Nginx Ingress, FluentD, ElasticSearch, Kibana 순서다.',
  },
  {
    id: 'ingress-gslb',
    type: 'fill-blank',
    section: 'Ingress',
    prompt: '여러 IP를 하나로 묶어 관리하고 트래픽 비율 조정이 가능한 DNS 기반 기술은 ____이다.',
    correctAnswer: ['GSLB', 'Global Server Load Balancing'],
    explanation: 'GSLB는 여러 IP를 묶고 Weight 기반 트래픽 조정을 가능하게 한다.',
  },
  {
    id: 'nginx-snippet-match',
    type: 'matching',
    section: 'Ingress',
    prompt: 'Nginx Ingress 어노테이션과 삽입 범위를 연결하세요.',
    pairs: [
      { left: 'server-snippet', right: 'server 블록' },
      { left: 'configuration-snippet', right: 'location 블록' },
    ],
    correctAnswer: {
      'server-snippet': 'server 블록',
      'configuration-snippet': 'location 블록',
    },
    explanation: 'server-snippet은 도메인 단위 server 블록, configuration-snippet은 경로 단위 location 블록에 삽입된다.',
  },
  {
    id: 'kustomize-structure',
    type: 'short-answer',
    section: '운영',
    prompt: 'Kustomize에서 환경별 설정을 효율적으로 관리하는 구조를 쓰세요.',
    correctAnswer: ['base + overlay', 'base와 overlay', 'base overlay', 'base(공통) + overlay(환경별)'],
    explanation: '문서에서는 `base` 공통 설정과 `overlay` 환경별 설정으로 dev/qa/prod를 관리한다고 설명한다.',
  },
  {
    id: 'gateway-api-warning',
    type: 'true-false',
    section: 'Ingress',
    prompt: 'Kingress/Gateway API 도입 시 기존 Nginx 전용 Annotation과의 호환성 검토가 필요하다.',
    correctAnswer: true,
    explanation: '문서의 향후 과제 섹션은 Kingress 도입 시 NodePort 기반 서비스와 기존 Nginx Annotation 호환성을 주의하라고 한다.',
  },
  {
    id: 'probe-liveness',
    type: 'multiple-choice',
    section: '헬스체크',
    prompt: 'Liveness Probe 실패 시 쿠버네티스가 수행하는 동작은?',
    options: ['파드를 재시작한다.', '파드를 엔드포인트에서만 제외한다.', '이미지를 다시 빌드한다.', 'Ingress 규칙을 삭제한다.'],
    correctAnswer: '파드를 재시작한다.',
    explanation: 'Liveness Probe는 파드 생존 여부를 확인하며 실패하면 쿠버네티스가 파드를 재시작한다.',
  },
  {
    id: 'probe-readiness',
    type: 'multiple-choice',
    section: '헬스체크',
    prompt: 'Readiness Probe 실패 시 가장 직접적인 결과는?',
    options: [
      '해당 파드를 엔드포인트에서 제외해 트래픽을 차단한다.',
      'Control Plane을 재시작한다.',
      'Docker 이미지를 삭제한다.',
      '모든 노드를 drain한다.',
    ],
    correctAnswer: '해당 파드를 엔드포인트에서 제외해 트래픽을 차단한다.',
    explanation: 'Readiness Probe는 실제 서비스 가능 상태를 확인하고 실패한 파드를 엔드포인트에서 제외한다.',
  },
  {
    id: 'resource-request',
    type: 'fill-blank',
    section: '리소스 관리',
    prompt: '파드가 보장받아야 하는 최소 사양은 Resource ____이다.',
    correctAnswer: ['Request', 'Requests'],
    explanation: 'Request는 파드가 보장받아야 하는 최소 사양이며 부족하면 Pending 상태가 될 수 있다.',
  },
  {
    id: 'deploy-strategy-match',
    type: 'matching',
    section: '배포 전략',
    prompt: '무중단 배포 방식과 설명을 연결하세요.',
    pairs: [
      { left: 'Rolling Update', right: '새 파드를 띄우고 검증되면 구버전을 삭제' },
      { left: 'Blue/Green', right: '두 버전을 동시에 띄운 뒤 트래픽을 한 번에 전환' },
      { left: 'Canary', right: '일부 비율의 사용자에게만 신버전을 먼저 노출' },
    ],
    correctAnswer: {
      'Rolling Update': '새 파드를 띄우고 검증되면 구버전을 삭제',
      'Blue/Green': '두 버전을 동시에 띄운 뒤 트래픽을 한 번에 전환',
      Canary: '일부 비율의 사용자에게만 신버전을 먼저 노출',
    },
    explanation: '문서에서는 Rolling Update, Blue/Green, Canary를 대표 무중단 배포 방식으로 정리한다.',
  },
  {
    id: 'operation-command-match',
    type: 'matching',
    section: 'kubectl 명령어',
    prompt: '운영 명령어와 용도를 연결하세요.',
    pairs: [
      { left: 'kubectl rollout status deploy/<name>', right: '배포 모니터링' },
      { left: 'kubectl scale deploy/<name> --replicas=N', right: '스케일 조정' },
      { left: 'kubectl rollout undo deploy/<name>', right: '롤백' },
      { left: 'kubectl drain [NODE_NAME]', right: '노드의 파드를 안전하게 이동' },
    ],
    correctAnswer: {
      'kubectl rollout status deploy/<name>': '배포 모니터링',
      'kubectl scale deploy/<name> --replicas=N': '스케일 조정',
      'kubectl rollout undo deploy/<name>': '롤백',
      'kubectl drain [NODE_NAME]': '노드의 파드를 안전하게 이동',
    },
    explanation: '문서의 실습 명령어와 요약 흐름은 rollout, scale, undo, drain의 용도를 구분한다.',
  },
  {
    id: 'kubectl-get-pods-namespace',
    type: 'true-false',
    section: 'kubectl 명령어',
    prompt: '`kubectl get pods -n <namespace>`는 특정 네임스페이스의 파드를 조회한다.',
    correctAnswer: true,
    explanation: '문서의 Service 관련 명령어 표에 특정 네임스페이스 파드 조회 명령으로 정리되어 있다.',
  },
];
